import type { Product, ProductFilter } from "@/types/dashboard";
import { daysUntilOut, getHealth, getRestockRecommendation, getStockStatus, productDecision, recommendedPrice } from "@/lib/dashboard/calculations";
import { money, percent } from "@/lib/dashboard/format";
import { Badge, EmptyState, ghostButtonStyle, Progress } from "./ui";

export function ProductTable({ products, mode = "product", onStock, onSale, onDelete }: { products: Product[]; mode?: "product" | "inventory"; onStock: (id: string) => void; onSale: (id: string) => void; onDelete: (id: string) => void }) {
  if (products.length === 0) return <EmptyState title="Belum ada produk" description="Tambahkan produk manual atau import CSV untuk mulai membaca profit dan stok." />;
  const columns = ["Produk", "Marketplace", "Harga", "Profit", "Stok", "Terjual", mode === "inventory" ? "Estimasi" : "Margin", "Status", "Aksi"];
  return <div style={{ overflowX: "auto", borderRadius: 18, border: "1px solid #dbe3ef", background: "#ffffff" }}><table style={{ width: "100%", borderCollapse: "collapse", minWidth: 980 }}><thead><tr style={{ background: "#f8fafc", textAlign: "left" }}>{columns.map((head) => <th key={head} style={{ padding: "14px 16px", color: "#64748b", fontSize: 12, fontWeight: 800, textTransform: "uppercase", borderBottom: "1px solid #e2e8f0", whiteSpace: "nowrap" }}>{head}</th>)}</tr></thead><tbody>{products.map((item) => {
    const health = getHealth(item); const stock = getStockStatus(item); const dayLeft = daysUntilOut(item); const safePrice = recommendedPrice(item); const restock = getRestockRecommendation(item);
    return <tr key={item.id} style={{ borderBottom: "1px solid #eef2f7" }}><td style={{ padding: 16, minWidth: 230 }}><strong>{item.name}</strong><div style={{ marginTop: 8, display: "flex", gap: 8, flexWrap: "wrap" }}><Badge label={health.label} tone={health.tone} /><Badge label={stock.label} tone={stock.tone} /></div><small style={{ display: "block", marginTop: 9, color: "#64748b" }}>{productDecision(item)} · Harga aman <b style={{ color: "#0f172a" }}>{money(safePrice)}</b></small></td><td style={{ padding: 16 }}><Badge label={item.marketplace || "Manual"} tone="blue" /></td><td style={{ padding: 16, whiteSpace: "nowrap" }}><small style={{ color: "#64748b" }}>Jual</small><br /><strong>{money(item.sellingPrice)}</strong></td><td style={{ padding: 16, whiteSpace: "nowrap" }}><small style={{ color: "#64748b" }}>Profit</small><br /><strong style={{ color: item.profit >= 0 ? "#0f766e" : "#b91c1c" }}>{money(item.profit)}</strong></td><td style={{ padding: 16, whiteSpace: "nowrap" }}><small style={{ color: "#64748b" }}>Stok</small><br /><strong>{item.stockRemaining}</strong></td><td style={{ padding: 16, whiteSpace: "nowrap" }}><small style={{ color: "#64748b" }}>Sold</small><br /><strong>{item.quantitySold}</strong></td><td style={{ padding: 16, minWidth: 140 }}>{mode === "inventory" ? <><small style={{ color: "#64748b" }}>Habis</small><br /><strong style={{ color: dayLeft !== null && dayLeft <= 7 ? "#b45309" : "#0f172a" }}>{dayLeft === null ? "-" : `${dayLeft} hari`}</strong></> : <><small style={{ color: "#64748b" }}>Margin</small><br /><strong>{percent(item.margin)}</strong><div style={{ marginTop: 8 }}><Progress value={Math.min(item.margin, 60) / 60 * 100} /></div></>}</td><td style={{ padding: 16, minWidth: 130 }}><Badge label={restock} tone={restock.toLowerCase().includes("restock") ? "success" : "muted"} /></td><td style={{ padding: 16, minWidth: 160 }}><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button onClick={() => onStock(item.id)} style={{ ...ghostButtonStyle, padding: "8px 11px", fontSize: 12 }}>Stok</button><button onClick={() => onSale(item.id)} style={{ ...ghostButtonStyle, padding: "8px 11px", fontSize: 12 }}>Jual</button><button onClick={() => onDelete(item.id)} style={{ padding: "8px 11px", borderRadius: 12, border: "1px solid #fecaca", background: "#fff5f5", color: "#b91c1c", cursor: "pointer", fontSize: 12, fontWeight: 800 }}>Hapus</button></div></td></tr>;
  })}</tbody></table></div>;
}

export function ProductCards({ products, onStock, onSale }: { products: Product[]; onStock: (id: string) => void; onSale: (id: string) => void }) {
  if (products.length === 0) return <EmptyState title="Belum ada produk" description="Tambah produk atau import CSV." />;
  return <div className="mobile-cards" style={{ display: "none", gap: 12 }}>{products.map((item) => <div key={item.id} style={{ padding: 16, borderRadius: 18, background: "#ffffff", border: "1px solid #dbe3ef" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><strong>{item.name}</strong><Badge label={item.marketplace || "Manual"} tone="blue" /></div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginTop: 14 }}><div><small style={{ color: "#64748b" }}>Profit</small><br /><b style={{ color: item.profit >= 0 ? "#0f766e" : "#b91c1c" }}>{money(item.profit)}</b></div><div><small style={{ color: "#64748b" }}>Margin</small><br /><b>{percent(item.margin)}</b></div><div><small style={{ color: "#64748b" }}>Stok</small><br /><b>{item.stockRemaining}</b></div><div><small style={{ color: "#64748b" }}>Keputusan</small><br /><b>{productDecision(item)}</b></div></div><div style={{ marginTop: 14, display: "flex", gap: 8 }}><button style={ghostButtonStyle} onClick={() => onStock(item.id)}>Stok</button><button style={ghostButtonStyle} onClick={() => onSale(item.id)}>Jual</button></div></div>)}</div>;
}

export function ProductFilters({ selectedFilter, onChange }: { selectedFilter: ProductFilter; onChange: (filter: ProductFilter) => void }) {
  const filters: [ProductFilter, string][] = [["all", "Semua"], ["loss", "Rugi"], ["fix", "Optimasi"], ["scale", "Scale"], ["stock", "Stok"]];
  return <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{filters.map(([key, label]) => <button key={key} onClick={() => onChange(key)} style={{ ...ghostButtonStyle, background: selectedFilter === key ? "#ecfdf5" : "#ffffff", color: selectedFilter === key ? "#047857" : "#0f172a" }}>{label}</button>)}</div>;
}
