import type { MIBundle, MICategory, MICreator, MILivestream, MIProduct, MIProviderStatus, MIResearchSource, MIShop, MIVideoAd } from "./types";

const now = new Date().toISOString();
const daysAgo = (days: number) => new Date(Date.now() - days * 86400000).toISOString();

export const MI_PRODUCTS: MIProduct[] = [
  {
    id: "p-tiktok-beauty-001",
    productName: "Parfum roll on viral 10ml",
    category: "Beauty",
    subcategory: "Fragrance",
    keyword: "parfum roll on viral",
    marketplace: "TikTok Shop",
    country: "ID",
    period: "week",
    priceMin: 15000,
    priceMax: 49000,
    sold7d: 7600,
    sold30d: 28600,
    revenue7d: 197600000,
    revenue30d: 743600000,
    growth7d: 38,
    growth30d: 72,
    sellerCount: 146,
    creatorCount: 82,
    videoCount: 394,
    liveCount: 47,
    adCount: 21,
    avgRating: 4.7,
    reviewCount: 4200,
    demandScore: 91,
    growthScore: 94,
    competitionScore: 55,
    opportunityScore: 86,
    saturationScore: 48,
    marginSignal: 76,
    signal: "viral",
    source: "Untungin V2 demo intelligence seed",
    sourceKind: "demo_seed",
    collectedAt: now,
    shopIds: ["s-tiktok-beauty-01", "s-tiktok-beauty-02"],
    creatorIds: ["c-beauty-01", "c-beauty-02"],
    videoIds: ["v-rollon-001", "v-rollon-002"],
    liveIds: ["l-beauty-001"],
    notes: "Data contoh/estimasi. Cocok untuk workflow riset manual, validasi supplier, dan uji konten pendek.",
  },
  {
    id: "p-tiktok-beauty-002",
    productName: "Sunscreen stick travel size",
    category: "Beauty",
    subcategory: "Skincare",
    keyword: "sunscreen stick",
    marketplace: "TikTok Shop",
    country: "ID",
    period: "week",
    priceMin: 28000,
    priceMax: 89000,
    sold7d: 5100,
    sold30d: 19200,
    revenue7d: 265200000,
    revenue30d: 998400000,
    growth7d: 25,
    growth30d: 54,
    sellerCount: 118,
    creatorCount: 66,
    videoCount: 276,
    liveCount: 31,
    adCount: 16,
    avgRating: 4.6,
    reviewCount: 3600,
    demandScore: 89,
    growthScore: 88,
    competitionScore: 62,
    opportunityScore: 80,
    saturationScore: 58,
    marginSignal: 70,
    signal: "rising",
    source: "Untungin V2 demo intelligence seed",
    sourceKind: "demo_seed",
    collectedAt: now,
    shopIds: ["s-tiktok-beauty-01"],
    creatorIds: ["c-beauty-01", "c-skincare-03"],
    videoIds: ["v-sunscreen-001"],
    liveIds: ["l-beauty-001"],
    notes: "Cek klaim BPOM, tekstur, dan potensi retur sebelum stok besar.",
  },
  {
    id: "p-shopee-home-001",
    productName: "Alat pel spray microfiber",
    category: "Home Living",
    subcategory: "Cleaning",
    keyword: "pel spray microfiber",
    marketplace: "Shopee",
    country: "ID",
    period: "week",
    priceMin: 39000,
    priceMax: 129000,
    sold7d: 3800,
    sold30d: 15400,
    revenue7d: 319200000,
    revenue30d: 1293600000,
    growth7d: 18,
    growth30d: 36,
    sellerCount: 74,
    creatorCount: 39,
    videoCount: 122,
    liveCount: 18,
    adCount: 11,
    avgRating: 4.5,
    reviewCount: 2900,
    demandScore: 82,
    growthScore: 79,
    competitionScore: 47,
    opportunityScore: 78,
    saturationScore: 42,
    marginSignal: 72,
    signal: "rising",
    source: "Untungin V2 demo intelligence seed",
    sourceKind: "demo_seed",
    collectedAt: now,
    shopIds: ["s-shopee-home-01"],
    creatorIds: ["c-home-01"],
    videoIds: ["v-pel-001"],
    liveIds: ["l-home-001"],
    notes: "Produk mudah didemokan dengan konten before-after.",
  },
  {
    id: "p-tiktok-fashion-001",
    productName: "Tas selempang puffy wanita",
    category: "Fashion",
    subcategory: "Bags",
    keyword: "tas puffy wanita",
    marketplace: "TikTok Shop",
    country: "ID",
    period: "week",
    priceMin: 45000,
    priceMax: 159000,
    sold7d: 5600,
    sold30d: 22200,
    revenue7d: 571200000,
    revenue30d: 2264400000,
    growth7d: 21,
    growth30d: 49,
    sellerCount: 210,
    creatorCount: 93,
    videoCount: 335,
    liveCount: 52,
    adCount: 30,
    avgRating: 4.4,
    reviewCount: 5100,
    demandScore: 86,
    growthScore: 83,
    competitionScore: 68,
    opportunityScore: 74,
    saturationScore: 70,
    marginSignal: 62,
    signal: "rising",
    source: "Untungin V2 demo intelligence seed",
    sourceKind: "demo_seed",
    collectedAt: now,
    shopIds: ["s-tiktok-fashion-01"],
    creatorIds: ["c-fashion-01", "c-fashion-02"],
    videoIds: ["v-tas-001"],
    liveIds: ["l-fashion-001"],
    notes: "Kompetisi tinggi; masuk hanya dengan variasi warna, foto, bonus, dan konten outfit.",
  },
  {
    id: "p-shopee-gadget-001",
    productName: "Casing HP MagSafe bening",
    category: "Aksesoris Gadget",
    subcategory: "Phone Case",
    keyword: "casing magsafe bening",
    marketplace: "Shopee",
    country: "ID",
    period: "today",
    priceMin: 19000,
    priceMax: 79000,
    sold7d: 4300,
    sold30d: 17100,
    revenue7d: 210700000,
    revenue30d: 837900000,
    growth7d: 29,
    growth30d: 44,
    sellerCount: 132,
    creatorCount: 45,
    videoCount: 160,
    liveCount: 22,
    adCount: 13,
    avgRating: 4.6,
    reviewCount: 3300,
    demandScore: 81,
    growthScore: 86,
    competitionScore: 52,
    opportunityScore: 79,
    saturationScore: 50,
    marginSignal: 74,
    signal: "rising",
    source: "Untungin V2 demo intelligence seed",
    sourceKind: "demo_seed",
    collectedAt: now,
    shopIds: ["s-shopee-gadget-01"],
    creatorIds: ["c-gadget-01"],
    videoIds: ["v-magsafe-001"],
    liveIds: ["l-gadget-001"],
    notes: "Validasi kompatibilitas model HP sebelum import stok.",
  },
  {
    id: "p-tiktok-kitchen-001",
    productName: "Mini chopper USB dapur",
    category: "Home Appliance",
    subcategory: "Kitchen Tools",
    keyword: "mini chopper usb",
    marketplace: "TikTok Shop",
    country: "ID",
    period: "today",
    priceMin: 59000,
    priceMax: 159000,
    sold7d: 3300,
    sold30d: 11800,
    revenue7d: 359700000,
    revenue30d: 1286200000,
    growth7d: 32,
    growth30d: 58,
    sellerCount: 89,
    creatorCount: 51,
    videoCount: 181,
    liveCount: 26,
    adCount: 14,
    avgRating: 4.5,
    reviewCount: 2400,
    demandScore: 84,
    growthScore: 89,
    competitionScore: 50,
    opportunityScore: 82,
    saturationScore: 46,
    marginSignal: 78,
    signal: "rising",
    source: "Untungin V2 demo intelligence seed",
    sourceKind: "demo_seed",
    collectedAt: now,
    shopIds: ["s-tiktok-home-01"],
    creatorIds: ["c-home-01"],
    videoIds: ["v-chopper-001", "v-chopper-002"],
    liveIds: ["l-home-001"],
    notes: "Cek kualitas baterai, garansi, dan aturan pengiriman.",
  },
  {
    id: "p-lazada-fashion-001",
    productName: "Hair claw clip premium isi 3",
    category: "Fashion",
    subcategory: "Accessories",
    keyword: "hair claw clip",
    marketplace: "Lazada",
    country: "ID",
    period: "today",
    priceMin: 7000,
    priceMax: 39000,
    sold7d: 4500,
    sold30d: 18400,
    revenue7d: 103500000,
    revenue30d: 423200000,
    growth7d: 17,
    growth30d: 31,
    sellerCount: 58,
    creatorCount: 34,
    videoCount: 92,
    liveCount: 11,
    adCount: 7,
    avgRating: 4.6,
    reviewCount: 2100,
    demandScore: 73,
    growthScore: 76,
    competitionScore: 39,
    opportunityScore: 77,
    saturationScore: 35,
    marginSignal: 83,
    signal: "rising",
    source: "Untungin V2 demo intelligence seed",
    sourceKind: "demo_seed",
    collectedAt: now,
    shopIds: ["s-lazada-fashion-01"],
    creatorIds: ["c-fashion-02"],
    videoIds: ["v-hairclip-001"],
    liveIds: [],
    notes: "Margin bisa naik lewat bundling isi 3/5 dan variasi warna.",
  },
  {
    id: "p-tokopedia-baby-001",
    productName: "Botol minum anak karakter",
    category: "Mom & Baby",
    subcategory: "Kids Bottle",
    keyword: "botol minum anak karakter",
    marketplace: "Tokopedia",
    country: "ID",
    period: "month",
    priceMin: 24000,
    priceMax: 99000,
    sold7d: 2600,
    sold30d: 12600,
    revenue7d: 159900000,
    revenue30d: 774900000,
    growth7d: 9,
    growth30d: 22,
    sellerCount: 64,
    creatorCount: 28,
    videoCount: 71,
    liveCount: 9,
    adCount: 5,
    avgRating: 4.7,
    reviewCount: 3100,
    demandScore: 80,
    growthScore: 67,
    competitionScore: 43,
    opportunityScore: 73,
    saturationScore: 40,
    marginSignal: 70,
    signal: "stable",
    source: "Untungin V2 demo intelligence seed",
    sourceKind: "demo_seed",
    collectedAt: now,
    shopIds: ["s-tokopedia-baby-01"],
    creatorIds: ["c-mom-01"],
    videoIds: ["v-botol-001"],
    liveIds: [],
    notes: "Demand stabil dan cocok untuk katalog evergreen.",
  },
  {
    id: "p-shopee-storage-001",
    productName: "Rak kosmetik acrylic",
    category: "Beauty Storage",
    subcategory: "Organizer",
    keyword: "rak kosmetik acrylic",
    marketplace: "Shopee",
    country: "ID",
    period: "month",
    priceMin: 29000,
    priceMax: 139000,
    sold7d: 2100,
    sold30d: 9800,
    revenue7d: 176400000,
    revenue30d: 823200000,
    growth7d: 12,
    growth30d: 28,
    sellerCount: 51,
    creatorCount: 30,
    videoCount: 84,
    liveCount: 8,
    adCount: 6,
    avgRating: 4.6,
    reviewCount: 1800,
    demandScore: 78,
    growthScore: 74,
    competitionScore: 41,
    opportunityScore: 76,
    saturationScore: 39,
    marginSignal: 75,
    signal: "rising",
    source: "Untungin V2 demo intelligence seed",
    sourceKind: "demo_seed",
    collectedAt: now,
    shopIds: ["s-shopee-home-01"],
    creatorIds: ["c-home-01", "c-beauty-02"],
    videoIds: ["v-rak-001"],
    liveIds: ["l-home-001"],
    notes: "Visual rapi untuk konten meja rias dan before-after.",
  },
  {
    id: "p-tokopedia-gift-001",
    productName: "Hampers snack premium custom",
    category: "Seasonal Gift",
    subcategory: "Hampers",
    keyword: "hampers snack premium",
    marketplace: "Tokopedia",
    country: "ID",
    period: "special_day",
    priceMin: 79000,
    priceMax: 299000,
    sold7d: 1400,
    sold30d: 8200,
    revenue7d: 264600000,
    revenue30d: 1549800000,
    growth7d: 41,
    growth30d: 77,
    sellerCount: 96,
    creatorCount: 24,
    videoCount: 65,
    liveCount: 6,
    adCount: 18,
    avgRating: 4.8,
    reviewCount: 1700,
    demandScore: 92,
    growthScore: 90,
    competitionScore: 54,
    opportunityScore: 85,
    saturationScore: 50,
    marginSignal: 84,
    signal: "seasonal",
    source: "Untungin V2 demo intelligence seed",
    sourceKind: "demo_seed",
    collectedAt: now,
    shopIds: ["s-tokopedia-gift-01"],
    creatorIds: ["c-gift-01"],
    videoIds: ["v-hampers-001"],
    liveIds: [],
    notes: "Naik saat Lebaran, Natal, wisuda, dan momen kantor.",
  },
  {
    id: "p-tiktok-party-001",
    productName: "Dekorasi ulang tahun anak paket lengkap",
    category: "Party Supplies",
    subcategory: "Birthday Decor",
    keyword: "dekorasi ulang tahun anak",
    marketplace: "TikTok Shop",
    country: "ID",
    period: "special_day",
    priceMin: 18000,
    priceMax: 99000,
    sold7d: 2900,
    sold30d: 13300,
    revenue7d: 169650000,
    revenue30d: 778050000,
    growth7d: 24,
    growth30d: 46,
    sellerCount: 69,
    creatorCount: 37,
    videoCount: 116,
    liveCount: 12,
    adCount: 8,
    avgRating: 4.5,
    reviewCount: 2200,
    demandScore: 79,
    growthScore: 84,
    competitionScore: 42,
    opportunityScore: 81,
    saturationScore: 38,
    marginSignal: 80,
    signal: "seasonal",
    source: "Untungin V2 demo intelligence seed",
    sourceKind: "demo_seed",
    collectedAt: now,
    shopIds: ["s-tiktok-party-01"],
    creatorIds: ["c-party-01"],
    videoIds: ["v-party-001"],
    liveIds: ["l-party-001"],
    notes: "Cocok untuk variasi tema dan paket bundling.",
  },
  {
    id: "p-lazada-electronics-001",
    productName: "Earphone bluetooth low latency",
    category: "Elektronik",
    subcategory: "Audio",
    keyword: "earphone bluetooth",
    marketplace: "Lazada",
    country: "ID",
    period: "week",
    priceMin: 49000,
    priceMax: 199000,
    sold7d: 3100,
    sold30d: 12200,
    revenue7d: 384400000,
    revenue30d: 1512800000,
    growth7d: 19,
    growth30d: 37,
    sellerCount: 88,
    creatorCount: 22,
    videoCount: 74,
    liveCount: 15,
    adCount: 19,
    avgRating: 4.4,
    reviewCount: 2600,
    demandScore: 86,
    growthScore: 79,
    competitionScore: 61,
    opportunityScore: 69,
    saturationScore: 62,
    marginSignal: 57,
    signal: "rising",
    source: "Untungin V2 demo intelligence seed",
    sourceKind: "demo_seed",
    collectedAt: now,
    shopIds: ["s-lazada-electronics-01"],
    creatorIds: ["c-gadget-01"],
    videoIds: ["v-earphone-001"],
    liveIds: ["l-gadget-001"],
    notes: "Cek retur, garansi, dan klaim low latency sebelum dijual.",
  },
];

export const MI_CATEGORIES: MICategory[] = [
  { id: "cat-beauty", name: "Beauty", parent: "Health & Beauty", marketplace: "TikTok Shop", country: "ID", productCount: 412, sold30d: 1240000, revenue30d: 68200000000, demandScore: 91, growthScore: 88, competitionScore: 66, opportunityScore: 78, topKeywords: ["parfum roll on", "sunscreen stick", "serum brightening", "lip tint"], notes: "Kategori besar, perlu diferensiasi klaim dan bukti hasil." },
  { id: "cat-home-living", name: "Home Living", parent: "Rumah Tangga", marketplace: "Shopee", country: "ID", productCount: 268, sold30d: 690000, revenue30d: 42100000000, demandScore: 84, growthScore: 79, competitionScore: 49, opportunityScore: 82, topKeywords: ["pel spray", "rak dapur", "organizer", "lampu aesthetic"], notes: "Produk demo before-after punya peluang konten kuat." },
  { id: "cat-fashion", name: "Fashion", parent: "Lifestyle", marketplace: "TikTok Shop", country: "ID", productCount: 620, sold30d: 1540000, revenue30d: 72400000000, demandScore: 86, growthScore: 81, competitionScore: 72, opportunityScore: 69, topKeywords: ["tas puffy", "hair claw", "cardigan", "sandal wanita"], notes: "Demand tinggi tapi cepat jenuh; perkuat visual dan variasi." },
  { id: "cat-gadget", name: "Aksesoris Gadget", parent: "Elektronik", marketplace: "Shopee", country: "ID", productCount: 312, sold30d: 760000, revenue30d: 38800000000, demandScore: 82, growthScore: 84, competitionScore: 58, opportunityScore: 76, topKeywords: ["casing magsafe", "charger fast", "tripod mini", "earphone low latency"], notes: "Cocok untuk bundling dan upsell model HP populer." },
  { id: "cat-seasonal", name: "Seasonal Gift", parent: "Hadiah", marketplace: "Tokopedia", country: "ID", productCount: 156, sold30d: 230000, revenue30d: 31900000000, demandScore: 88, growthScore: 90, competitionScore: 53, opportunityScore: 84, topKeywords: ["hampers snack", "hampers kantor", "kado wisuda", "paket lebaran"], notes: "Butuh kalender campaign dan stok musiman." },
  { id: "cat-mom-baby", name: "Mom & Baby", parent: "Keluarga", marketplace: "Tokopedia", country: "ID", productCount: 210, sold30d: 410000, revenue30d: 25500000000, demandScore: 80, growthScore: 68, competitionScore: 45, opportunityScore: 74, topKeywords: ["botol anak", "alat makan bayi", "tas stroller", "mainan edukasi"], notes: "Lebih evergreen; penting jaga kualitas dan keamanan material." },
];

export const MI_SHOPS: MIShop[] = [
  { id: "s-tiktok-beauty-01", shopName: "Glow Lab Official", marketplace: "TikTok Shop", country: "ID", categoryFocus: "Beauty", productCount: 42, sold30d: 94000, revenue30d: 5200000000, avgPrice: 55300, avgRating: 4.7, reviewCount: 12600, followers: 168000, liveCount: 62, adCount: 34, topProductId: "p-tiktok-beauty-001", opportunityGap: "Konten UGC kuat, tetapi bundling masih tipis.", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now, notes: "Benchmark untuk beauty live dan affiliate." },
  { id: "s-tiktok-beauty-02", shopName: "Aroma Daily Store", marketplace: "TikTok Shop", country: "ID", categoryFocus: "Fragrance", productCount: 18, sold30d: 41000, revenue30d: 1180000000, avgPrice: 28800, avgRating: 4.6, reviewCount: 5300, followers: 74000, liveCount: 29, adCount: 11, topProductId: "p-tiktok-beauty-001", opportunityGap: "Harga agresif; peluang masuk lewat paket isi 3.", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now },
  { id: "s-shopee-home-01", shopName: "Rumah Rapi ID", marketplace: "Shopee", country: "ID", categoryFocus: "Home Living", productCount: 86, sold30d: 67000, revenue30d: 4700000000, avgPrice: 70100, avgRating: 4.6, reviewCount: 18800, followers: 92000, liveCount: 21, adCount: 17, topProductId: "p-shopee-home-001", opportunityGap: "Review negatif banyak soal sparepart; bisa menang dengan garansi.", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now },
  { id: "s-tiktok-fashion-01", shopName: "OOTD Corner", marketplace: "TikTok Shop", country: "ID", categoryFocus: "Fashion", productCount: 112, sold30d: 138000, revenue30d: 10100000000, avgPrice: 73200, avgRating: 4.4, reviewCount: 24400, followers: 256000, liveCount: 88, adCount: 52, topProductId: "p-tiktok-fashion-001", opportunityGap: "Variasi tinggi tapi foto produk kurang konsisten.", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now },
  { id: "s-shopee-gadget-01", shopName: "CaseHub Nusantara", marketplace: "Shopee", country: "ID", categoryFocus: "Aksesoris Gadget", productCount: 154, sold30d: 97000, revenue30d: 3900000000, avgPrice: 40200, avgRating: 4.5, reviewCount: 21300, followers: 121000, liveCount: 16, adCount: 28, topProductId: "p-shopee-gadget-001", opportunityGap: "Peluang SEO listing per model HP masih besar.", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now },
  { id: "s-tokopedia-gift-01", shopName: "HampersKita", marketplace: "Tokopedia", country: "ID", categoryFocus: "Seasonal Gift", productCount: 36, sold30d: 18200, revenue30d: 4300000000, avgPrice: 236000, avgRating: 4.8, reviewCount: 3800, followers: 44000, liveCount: 4, adCount: 22, topProductId: "p-tokopedia-gift-001", opportunityGap: "Bisa diserang dengan custom corporate pack dan SLA pengiriman.", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now },
  { id: "s-tiktok-home-01", shopName: "Dapur Cepat Store", marketplace: "TikTok Shop", country: "ID", categoryFocus: "Home Appliance", productCount: 31, sold30d: 35800, revenue30d: 3900000000, avgPrice: 109000, avgRating: 4.5, reviewCount: 7200, followers: 83000, liveCount: 35, adCount: 14, topProductId: "p-tiktok-kitchen-001", opportunityGap: "Banyak komplain baterai; garansi bisa jadi pembeda.", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now },
];

export const MI_CREATORS: MICreator[] = [
  { id: "c-beauty-01", creatorName: "Nadia Beauty Notes", handle: "@nadiabeautynotes", marketplace: "TikTok Shop", country: "ID", categoryFocus: "Beauty", followers: 248000, avgViews: 185000, engagementRate: 5.8, productCount: 34, sold30d: 18200, revenue30d: 920000000, commissionRate: 12, fitScore: 91, topProductId: "p-tiktok-beauty-001", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now, notes: "Bagus untuk produk beauty low-mid price." },
  { id: "c-beauty-02", creatorName: "Ayu Review Harian", handle: "@ayureviewharian", marketplace: "TikTok Shop", country: "ID", categoryFocus: "Beauty Storage", followers: 96000, avgViews: 72000, engagementRate: 6.2, productCount: 22, sold30d: 6400, revenue30d: 330000000, commissionRate: 10, fitScore: 82, topProductId: "p-shopee-storage-001", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now },
  { id: "c-home-01", creatorName: "Rumah Rapi Review", handle: "@rumahrapireview", marketplace: "TikTok Shop", country: "ID", categoryFocus: "Home Living", followers: 176000, avgViews: 118000, engagementRate: 4.9, productCount: 41, sold30d: 14800, revenue30d: 1240000000, commissionRate: 9, fitScore: 88, topProductId: "p-shopee-home-001", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now, notes: "Kuat untuk demo before-after." },
  { id: "c-fashion-01", creatorName: "Mira OOTD", handle: "@miraootd", marketplace: "TikTok Shop", country: "ID", categoryFocus: "Fashion", followers: 320000, avgViews: 210000, engagementRate: 4.1, productCount: 58, sold30d: 27400, revenue30d: 2100000000, commissionRate: 15, fitScore: 84, topProductId: "p-tiktok-fashion-001", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now },
  { id: "c-gadget-01", creatorName: "Dimas Gadget Murah", handle: "@dimasgadgetmurah", marketplace: "Shopee", country: "ID", categoryFocus: "Aksesoris Gadget", followers: 142000, avgViews: 89000, engagementRate: 3.8, productCount: 45, sold30d: 11600, revenue30d: 770000000, commissionRate: 7, fitScore: 79, topProductId: "p-shopee-gadget-001", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now },
  { id: "c-gift-01", creatorName: "Kado Cantik Studio", handle: "@kadocantikstudio", marketplace: "Tokopedia", country: "ID", categoryFocus: "Seasonal Gift", followers: 68000, avgViews: 46000, engagementRate: 5.1, productCount: 16, sold30d: 2400, revenue30d: 620000000, commissionRate: 8, fitScore: 76, topProductId: "p-tokopedia-gift-001", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now },
  { id: "c-party-01", creatorName: "Ide Pesta Anak", handle: "@idepestaanak", marketplace: "TikTok Shop", country: "ID", categoryFocus: "Party Supplies", followers: 84000, avgViews: 63000, engagementRate: 5.6, productCount: 19, sold30d: 5200, revenue30d: 260000000, commissionRate: 11, fitScore: 83, topProductId: "p-tiktok-party-001", source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", collectedAt: now },
];

export const MI_VIDEOS: MIVideoAd[] = [
  { id: "v-rollon-001", title: "Parfum mini yang wanginya tahan seharian", format: "affiliate_video", productId: "p-tiktok-beauty-001", creatorId: "c-beauty-01", marketplace: "TikTok Shop", country: "ID", views: 1800000, likes: 94000, comments: 6200, shares: 8200, ctr: 3.8, cvr: 2.1, gmvEstimate: 185000000, hook: "Aku kira parfum murah pasti cepat hilang...", cta: "Cek keranjang kuning sebelum varian favorit habis", durationSec: 28, postedAt: daysAgo(4), source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", notes: "Hook problem-solution kuat." },
  { id: "v-rollon-002", title: "Tes parfum roll on di motor dan kantor", format: "organic", productId: "p-tiktok-beauty-001", creatorId: "c-beauty-02", marketplace: "TikTok Shop", country: "ID", views: 640000, likes: 31000, comments: 2100, shares: 2800, ctr: 2.9, cvr: 1.4, gmvEstimate: 58000000, hook: "Aku pakai dari pagi sampai pulang kerja", cta: "Simpan dulu biar tidak lupa", durationSec: 35, postedAt: daysAgo(6), source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed" },
  { id: "v-sunscreen-001", title: "Sunscreen stick buat reapply tanpa tangan lengket", format: "ad", productId: "p-tiktok-beauty-002", creatorId: "c-beauty-01", marketplace: "TikTok Shop", country: "ID", views: 1200000, likes: 58000, comments: 3900, shares: 5100, ctr: 4.2, cvr: 1.8, gmvEstimate: 132000000, hook: "Reapply sunscreen di luar rumah sering bikin malas", cta: "Klik promo hari ini", durationSec: 24, postedAt: daysAgo(3), source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed" },
  { id: "v-pel-001", title: "Lantai berminyak jadi bersih dalam 30 detik", format: "shop_video", productId: "p-shopee-home-001", creatorId: "c-home-01", marketplace: "Shopee", country: "ID", views: 760000, likes: 28000, comments: 1800, shares: 2400, ctr: 2.4, cvr: 1.6, gmvEstimate: 76000000, hook: "Kalau lantai rumah sering lengket, coba cara ini", cta: "Ambil voucher toko", durationSec: 41, postedAt: daysAgo(8), source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed" },
  { id: "v-tas-001", title: "Tas puffy yang masuk semua outfit", format: "affiliate_video", productId: "p-tiktok-fashion-001", creatorId: "c-fashion-01", marketplace: "TikTok Shop", country: "ID", views: 1500000, likes: 73000, comments: 4500, shares: 6900, ctr: 3.1, cvr: 1.5, gmvEstimate: 168000000, hook: "Tas ini bikin outfit polos kelihatan niat", cta: "Pilih warna sebelum diskon selesai", durationSec: 32, postedAt: daysAgo(5), source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed" },
  { id: "v-chopper-001", title: "Bumbu dapur halus tanpa ribet", format: "organic", productId: "p-tiktok-kitchen-001", creatorId: "c-home-01", marketplace: "TikTok Shop", country: "ID", views: 980000, likes: 42000, comments: 3300, shares: 3900, ctr: 3.4, cvr: 1.9, gmvEstimate: 121000000, hook: "Capek ngulek tiap masak?", cta: "Cek paket garansi toko", durationSec: 38, postedAt: daysAgo(2), source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed" },
  { id: "v-hampers-001", title: "Hampers kantor yang terlihat mahal", format: "ad", productId: "p-tokopedia-gift-001", creatorId: "c-gift-01", marketplace: "Tokopedia", country: "ID", views: 330000, likes: 12000, comments: 840, shares: 1300, ctr: 2.8, cvr: 2.4, gmvEstimate: 92000000, hook: "Butuh hampers rapi untuk klien?", cta: "Chat toko untuk custom logo", durationSec: 30, postedAt: daysAgo(11), source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed" },
  { id: "v-earphone-001", title: "Earphone murah buat gaming ringan", format: "ad", productId: "p-lazada-electronics-001", creatorId: "c-gadget-01", marketplace: "Lazada", country: "ID", views: 420000, likes: 14000, comments: 1200, shares: 900, ctr: 2.5, cvr: 1.2, gmvEstimate: 64000000, hook: "Latency kecil tapi harga masih masuk", cta: "Cek flash sale", durationSec: 27, postedAt: daysAgo(7), source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed" },
];

export const MI_LIVES: MILivestream[] = [
  { id: "l-beauty-001", title: "Beauty Payday Live", hostName: "Glow Lab Official", hostType: "seller", marketplace: "TikTok Shop", country: "ID", categoryFocus: "Beauty", productIds: ["p-tiktok-beauty-001", "p-tiktok-beauty-002"], viewersPeak: 8400, durationMin: 182, soldUnits: 3900, revenue: 214000000, conversionRate: 3.4, liveDate: daysAgo(2), source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", notes: "Flash bundle per 20 menit menjaga urgency." },
  { id: "l-home-001", title: "Demo Rumah Rapi Weekend", hostName: "Rumah Rapi Review", hostType: "creator", marketplace: "TikTok Shop", country: "ID", categoryFocus: "Home Living", productIds: ["p-shopee-home-001", "p-tiktok-kitchen-001", "p-shopee-storage-001"], viewersPeak: 5200, durationMin: 146, soldUnits: 1700, revenue: 156000000, conversionRate: 2.8, liveDate: daysAgo(3), source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", notes: "Demo langsung menaikkan trust produk home appliance." },
  { id: "l-fashion-001", title: "OOTD Flash Sale", hostName: "OOTD Corner", hostType: "seller", marketplace: "TikTok Shop", country: "ID", categoryFocus: "Fashion", productIds: ["p-tiktok-fashion-001"], viewersPeak: 11600, durationMin: 240, soldUnits: 5200, revenue: 530000000, conversionRate: 3.1, liveDate: daysAgo(1), source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed", notes: "Variasi warna ditampilkan lewat model berbeda." },
  { id: "l-gadget-001", title: "Aksesoris HP Murah", hostName: "Dimas Gadget Murah", hostType: "creator", marketplace: "Shopee", country: "ID", categoryFocus: "Aksesoris Gadget", productIds: ["p-shopee-gadget-001", "p-lazada-electronics-001"], viewersPeak: 3400, durationMin: 96, soldUnits: 1100, revenue: 73000000, conversionRate: 2.2, liveDate: daysAgo(6), source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed" },
  { id: "l-party-001", title: "Ide Pesta Anak Hemat", hostName: "Ide Pesta Anak", hostType: "creator", marketplace: "TikTok Shop", country: "ID", categoryFocus: "Party Supplies", productIds: ["p-tiktok-party-001"], viewersPeak: 2900, durationMin: 88, soldUnits: 860, revenue: 49000000, conversionRate: 2.6, liveDate: daysAgo(9), source: "Untungin V2 demo intelligence seed", sourceKind: "demo_seed" },
];

export const MI_SOURCES: MIResearchSource[] = [
  {
    id: "src-tiktok-parfum-search",
    title: "TikTok Shop keyword parfum roll on viral",
    marketplace: "TikTok Shop",
    sourceType: "search",
    sourceUrl: "https://www.tiktok.com/search?q=parfum%20roll%20on%20viral",
    keyword: "parfum roll on viral",
    category: "Beauty",
    country: "ID",
    status: "active",
    extractedCount: 0,
    notes: "Contoh source link. Link disimpan sebagai referensi riset, bukan scraping otomatis.",
    createdAt: daysAgo(1),
    updatedAt: now,
  },
  {
    id: "src-shopee-pel-search",
    title: "Shopee keyword pel lantai viral",
    marketplace: "Shopee",
    sourceType: "search",
    sourceUrl: "https://shopee.co.id/search?keyword=pel%20lantai%20viral",
    keyword: "pel lantai viral",
    category: "Home Living",
    country: "ID",
    status: "queued",
    extractedCount: 0,
    notes: "Gunakan sebagai daftar antrean riset manual/partner feed.",
    createdAt: daysAgo(2),
    updatedAt: now,
  },
];

export const MI_PROVIDERS: MIProviderStatus[] = [
  { id: "demo-v2", name: "V2 Market Intelligence demo", kind: "demo_seed", enabled: true, status: "demo", message: "Produk, kategori, toko, kreator, video & ads, dan live commerce siap untuk demo." },
];

export const MI_SAMPLE_BUNDLE: MIBundle = {
  products: MI_PRODUCTS,
  categories: MI_CATEGORIES,
  shops: MI_SHOPS,
  creators: MI_CREATORS,
  videos: MI_VIDEOS,
  lives: MI_LIVES,
  sources: MI_SOURCES,
  providers: MI_PROVIDERS,
  errors: [],
  generatedAt: now,
};
