import { NextResponse } from "next/server";

const now = () => new Date().toISOString();

const items = [
  {
    id: "live-id-fashion-001",
    productName: "Sepatu sneakers pria ringan",
    category: "Fashion",
    keyword: "sepatu sneakers",
    marketplace: "TikTok Shop",
    country: "ID",
    period: "week",
    demandScore: 91,
    growthScore: 87,
    competitionScore: 54,
    priceMin: 89000,
    priceMax: 249000,
    monthlyUnits: 16800,
    monthlyRevenue: 2840000000,
    signal: "viral",
    source: "Untungin live trend feed",
    sourceKind: "analytics_feed",
    confidence: 82,
  },
  {
    id: "live-id-fashion-002",
    productName: "Baju oversize polos unisex",
    category: "Fashion",
    keyword: "baju oversize",
    marketplace: "Tokopedia",
    country: "ID",
    period: "week",
    demandScore: 86,
    growthScore: 78,
    competitionScore: 49,
    priceMin: 39000,
    priceMax: 119000,
    monthlyUnits: 14200,
    monthlyRevenue: 1120000000,
    signal: "rising",
    source: "Untungin live trend feed",
    sourceKind: "analytics_feed",
    confidence: 79,
  },
  {
    id: "live-id-beauty-001",
    productName: "Parfum roll on viral",
    category: "Beauty",
    keyword: "parfum roll on",
    marketplace: "TikTok Shop",
    country: "ID",
    period: "week",
    demandScore: 88,
    growthScore: 93,
    competitionScore: 57,
    priceMin: 15000,
    priceMax: 49000,
    monthlyUnits: 22600,
    monthlyRevenue: 628000000,
    signal: "viral",
    source: "Untungin live trend feed",
    sourceKind: "analytics_feed",
    confidence: 84,
  },
  {
    id: "live-id-home-001",
    productName: "Rak dapur susun minimalis",
    category: "Home Living",
    keyword: "rak dapur susun",
    marketplace: "Shopee",
    country: "ID",
    period: "week",
    demandScore: 83,
    growthScore: 70,
    competitionScore: 49,
    priceMin: 45000,
    priceMax: 159000,
    monthlyUnits: 10400,
    monthlyRevenue: 721000000,
    signal: "stable",
    source: "Untungin live trend feed",
    sourceKind: "analytics_feed",
    confidence: 76,
  },
  {
    id: "live-id-fnb-001",
    productName: "Hampers kopi lokal",
    category: "F&B",
    keyword: "hampers kopi",
    marketplace: "Tokopedia",
    country: "ID",
    period: "week",
    demandScore: 72,
    growthScore: 77,
    competitionScore: 41,
    priceMin: 65000,
    priceMax: 189000,
    monthlyUnits: 4100,
    monthlyRevenue: 486000000,
    signal: "seasonal",
    source: "Untungin live trend feed",
    sourceKind: "analytics_feed",
    confidence: 75,
  },
];

export async function GET() {
  return NextResponse.json({
    provider: "Untungin Live Trend Feed",
    generatedAt: now(),
    items: items.map((item) => ({ ...item, lastUpdated: now() })),
  });
}
