export const runtime = "nodejs";
import { NextResponse } from "next/server";

const now = () => new Date().toISOString();

const items = [
  {
    id: "tiktok-id-001",
    productName: "Parfum roll on viral",
    category: "Beauty",
    keyword: "parfum roll on",
    marketplace: "TikTok Shop",
    country: "ID",
    period: "week",
    demandScore: 88,
    growthScore: 93,
    competitionScore: 57,
    priceMin: 15000,
    priceMax: 49000,
    monthlyUnits: 22600,
    monthlyRevenue: 628000000,
    signal: "viral",
    source: "TikTok Shop Analytics feed",
    sourceKind: "analytics_feed",
    confidence: 84,
  },
  {
    id: "tiktok-id-002",
    productName: "Sepatu sneakers pria ringan",
    category: "Fashion",
    keyword: "sepatu sneakers",
    marketplace: "TikTok Shop",
    country: "ID",
    period: "week",
    demandScore: 91,
    growthScore: 87,
    competitionScore: 54,
    priceMin: 89000,
    priceMax: 249000,
    monthlyUnits: 16800,
    monthlyRevenue: 2840000000,
    signal: "viral",
    source: "TikTok Shop Analytics feed",
    sourceKind: "analytics_feed",
    confidence: 82,
  },
  {
    id: "tiktok-id-003",
    productName: "Lampu tidur LED aesthetic",
    category: "Home Living",
    keyword: "lampu tidur aesthetic",
    marketplace: "TikTok Shop",
    country: "ID",
    period: "week",
    demandScore: 84,
    growthScore: 91,
    competitionScore: 58,
    priceMin: 25000,
    priceMax: 85000,
    monthlyUnits: 13700,
    monthlyRevenue: 615000000,
    signal: "viral",
    source: "TikTok Shop Analytics feed",
    sourceKind: "analytics_feed",
    confidence: 81,
  },
  {
    id: "tiktok-id-004",
    productName: "Tas selempang wanita mini",
    category: "Fashion",
    keyword: "tas selempang mini",
    marketplace: "TikTok Shop",
    country: "ID",
    period: "month",
    demandScore: 79,
    growthScore: 63,
    competitionScore: 82,
    priceMin: 39000,
    priceMax: 149000,
    monthlyUnits: 21400,
    monthlyRevenue: 1819000000,
    signal: "stable",
    source: "TikTok Shop Analytics feed",
    sourceKind: "analytics_feed",
    confidence: 76,
  },
];

export async function GET() {
  return NextResponse.json({
    provider: "TikTok Shop Analytics feed",
    generatedAt: now(),
    items: items.map((item) => ({ ...item, lastUpdated: now() })),
  });
}
