import { NextResponse } from "next/server";

const now = () => new Date().toISOString();

const items = [
  {
    id: "tokopedia-id-001",
    productName: "Baju oversize polos unisex",
    category: "Fashion",
    keyword: "baju oversize",
    marketplace: "Tokopedia",
    country: "ID",
    period: "week",
    demandScore: 86,
    growthScore: 78,
    competitionScore: 49,
    priceMin: 39000,
    priceMax: 119000,
    monthlyUnits: 14200,
    monthlyRevenue: 1120000000,
    signal: "rising",
    source: "Tokopedia Analytics feed",
    sourceKind: "analytics_feed",
    confidence: 79,
  },
  {
    id: "tokopedia-id-002",
    productName: "Hampers kopi lokal",
    category: "F&B",
    keyword: "hampers kopi",
    marketplace: "Tokopedia",
    country: "ID",
    period: "week",
    demandScore: 72,
    growthScore: 77,
    competitionScore: 41,
    priceMin: 65000,
    priceMax: 189000,
    monthlyUnits: 4100,
    monthlyRevenue: 486000000,
    signal: "seasonal",
    source: "Tokopedia Analytics feed",
    sourceKind: "analytics_feed",
    confidence: 75,
  },
  {
    id: "tokopedia-id-003",
    productName: "Botol minum anak anti bocor",
    category: "Mom & Baby",
    keyword: "botol minum anak",
    marketplace: "Tokopedia",
    country: "ID",
    period: "week",
    demandScore: 81,
    growthScore: 65,
    competitionScore: 44,
    priceMin: 24000,
    priceMax: 69000,
    monthlyUnits: 9600,
    monthlyRevenue: 392000000,
    signal: "stable",
    source: "Tokopedia Analytics feed",
    sourceKind: "analytics_feed",
    confidence: 77,
  },
  {
    id: "tokopedia-id-004",
    productName: "Kopi susu literan",
    category: "F&B",
    keyword: "kopi susu literan",
    marketplace: "Tokopedia",
    country: "ID",
    period: "month",
    demandScore: 75,
    growthScore: 71,
    competitionScore: 37,
    priceMin: 35000,
    priceMax: 89000,
    monthlyUnits: 5200,
    monthlyRevenue: 314000000,
    signal: "rising",
    source: "Tokopedia Analytics feed",
    sourceKind: "analytics_feed",
    confidence: 76,
  },
];

export async function GET() {
  return NextResponse.json({
    provider: "Tokopedia Analytics feed",
    generatedAt: now(),
    items: items.map((item) => ({ ...item, lastUpdated: now() })),
  });
}
