import { useMemo, useState } from "react";
import type React from "react";
import type { Expense, Product, StockMoveType } from "@/types/dashboard";
import { EXPENSE_CATEGORIES } from "@/lib/dashboard/constants";
import { money } from "@/lib/dashboard/format";
import { useDashboardLocale } from "@/lib/dashboard/i18n";
import { Badge, cardStyle, ctaButtonStyle, ghostButtonStyle, inputStyle, StatCard } from "./ui";

export type ProductFormState = { productName: string; costPrice: string; sellingPrice: string; stockInitial: string; quantitySold: string; otherCost: string; marketplace: string };
export type ExpenseFormState = { label: string; category: string; amount: string; date: string; notes: string };

const COPY = {
  id: { inputProduct: "Input Produk", addProductTitle: "Tambah / catat penjualan produk", productHint: "Ketik produk baru, atau pilih produk tersimpan di bawah agar stok dan profit tersambung otomatis.", productName: "Nama produk", savedProducts: "Produk tersimpan", clickToPick: "Klik untuk pilih", noMatch: "Tidak ada yang cocok", stock: "stok", sold: "terjual", pick: "Pilih", noSaved: "Belum ada produk tersimpan. Setelah produk pertama disimpan, namanya akan muncul otomatis di sini.", typeOther: "Ketik nama lain atau ubah marketplace untuk mencari produk tersimpan.", selected: "Produk dipilih:", stockAvailable: "stok tersedia", soldField: "Terjual", selectedHint: "Isi kolom", selectedHint2: "lalu simpan untuk mengurangi stok otomatis.", cost: "Modal per produk", price: "Harga jual", stockAvailableField: "Stok tersedia", initialStock: "Stok awal", otherCost: "Biaya lain", saving: "Menyimpan...", saveSaleAdd: "Simpan penjualan & tambah lagi", saveAdd: "Simpan & tambah lagi", saveSaleFinish: "Simpan penjualan & selesai", saveFinish: "Simpan & selesai", expenseEngine: "Expense Engine", recordExpense: "Catat biaya operasional", expenseDesc: "Pisahkan biaya ads, packing, fee marketplace, tools, gaji, dan operasional agar cashflow tidak semu.", expenseName: "Nama biaya", amount: "Nominal", optionalNotes: "Catatan opsional", addExpense: "Tambah biaya", cashflowReal: "Cashflow Real", netCashflow: "cashflow bersih", moneyIn: "Uang masuk", fromSales: "Dari sales produk", productProfit: "Profit produk", beforeExpense: "Sebelum biaya operasional", moneyOut: "Uang keluar", expenseHelper: "Ads, fee, packing, ops", stockMove: "Stock Movement", updateStock: "Update stok", stockDesc: "Stok masuk, keluar manual, atau stok opname.", chooseProduct: "Pilih produk", stockIn: "Stok masuk / restock", stockOut: "Stok keluar manual", stockAdjust: "Set stok aktual", qty: "Jumlah", sales: "Sales", recordSale: "Catat penjualan", saleDesc: "Penjualan otomatis mengurangi stok dan update profit.", qtySold: "Qty terjual", extraCost: "Biaya tambahan transaksi", saveSale: "Simpan penjualan" },
  en: { inputProduct: "Product Input", addProductTitle: "Add product / record product sale", productHint: "Type a new product, or select a saved product below so stock and profit stay connected automatically.", productName: "Product name", savedProducts: "Saved products", clickToPick: "Click to select", noMatch: "No match", stock: "stock", sold: "sold", pick: "Select", noSaved: "No saved products yet. After the first product is saved, its name will appear here automatically.", typeOther: "Type another name or change marketplace to find saved products.", selected: "Selected product:", stockAvailable: "available stock", soldField: "Sold", selectedHint: "Fill the", selectedHint2: "field, then save to reduce stock automatically.", cost: "Cost per product", price: "Selling price", stockAvailableField: "Available stock", initialStock: "Initial stock", otherCost: "Other cost", saving: "Saving...", saveSaleAdd: "Save sale & add another", saveAdd: "Save & add another", saveSaleFinish: "Save sale & finish", saveFinish: "Save & finish", expenseEngine: "Expense Engine", recordExpense: "Record operating expense", expenseDesc: "Separate ads, packing, marketplace fees, tools, payroll, and operations so cash flow stays accurate.", expenseName: "Expense name", amount: "Amount", optionalNotes: "Optional notes", addExpense: "Add expense", cashflowReal: "Real Cash Flow", netCashflow: "net cash flow", moneyIn: "Money in", fromSales: "From product sales", productProfit: "Product profit", beforeExpense: "Before operating expenses", moneyOut: "Money out", expenseHelper: "Ads, fees, packing, ops", stockMove: "Stock Movement", updateStock: "Update stock", stockDesc: "Stock in, manual stock out, or stock opname.", chooseProduct: "Choose product", stockIn: "Stock in / restock", stockOut: "Manual stock out", stockAdjust: "Set actual stock", qty: "Quantity", sales: "Sales", recordSale: "Record sale", saleDesc: "Sales automatically reduce stock and update profit.", qtySold: "Qty sold", extraCost: "Additional transaction cost", saveSale: "Save sale" },
  ms: { inputProduct: "Input Produk", addProductTitle: "Tambah produk / catat jualan produk", productHint: "Taip produk baharu, atau pilih produk tersimpan di bawah supaya stok dan profit tersambung automatik.", productName: "Nama produk", savedProducts: "Produk tersimpan", clickToPick: "Klik untuk pilih", noMatch: "Tiada padanan", stock: "stok", sold: "terjual", pick: "Pilih", noSaved: "Belum ada produk tersimpan. Selepas produk pertama disimpan, namanya akan muncul automatik di sini.", typeOther: "Taip nama lain atau ubah marketplace untuk mencari produk tersimpan.", selected: "Produk dipilih:", stockAvailable: "stok tersedia", soldField: "Terjual", selectedHint: "Isi lajur", selectedHint2: "lalu simpan untuk mengurangkan stok automatik.", cost: "Kos per produk", price: "Harga jual", stockAvailableField: "Stok tersedia", initialStock: "Stok awal", otherCost: "Kos lain", saving: "Menyimpan...", saveSaleAdd: "Simpan jualan & tambah lagi", saveAdd: "Simpan & tambah lagi", saveSaleFinish: "Simpan jualan & selesai", saveFinish: "Simpan & selesai", expenseEngine: "Enjin Belanja", recordExpense: "Catat belanja operasi", expenseDesc: "Pisahkan kos iklan, packing, fi marketplace, tools, gaji, dan operasi supaya cashflow tepat.", expenseName: "Nama belanja", amount: "Jumlah", optionalNotes: "Catatan opsional", addExpense: "Tambah belanja", cashflowReal: "Aliran Tunai Sebenar", netCashflow: "aliran tunai bersih", moneyIn: "Wang masuk", fromSales: "Daripada jualan produk", productProfit: "Profit produk", beforeExpense: "Sebelum belanja operasi", moneyOut: "Wang keluar", expenseHelper: "Iklan, fi, packing, ops", stockMove: "Pergerakan Stok", updateStock: "Kemas kini stok", stockDesc: "Stok masuk, keluar manual, atau stock opname.", chooseProduct: "Pilih produk", stockIn: "Stok masuk / restock", stockOut: "Stok keluar manual", stockAdjust: "Set stok sebenar", qty: "Jumlah", sales: "Jualan", recordSale: "Catat jualan", saleDesc: "Jualan automatik mengurangkan stok dan kemas kini profit.", qtySold: "Qty terjual", extraCost: "Kos transaksi tambahan", saveSale: "Simpan jualan" },
};

export function ProductForm({ form, loading, products, onChange, onSubmit, onFinish }: { form: ProductFormState; loading: boolean; products: Product[]; onChange: (form: ProductFormState) => void; onSubmit: (event: React.FormEvent) => void; onFinish: () => void; }) {
  const locale = useDashboardLocale(); const c = COPY[locale];
  const [productPickerOpen, setProductPickerOpen] = useState(false);
  const normalizedName = form.productName.trim().toLowerCase();
  const productOptions = useMemo(() => Array.from(new Map(products.map((item) => [`${item.name.trim().toLowerCase()}-${item.marketplace || "Manual"}`, item])).values()), [products]);
  const matchedProduct = productOptions.find((item) => item.name.trim().toLowerCase() === normalizedName && (item.marketplace || "Manual") === form.marketplace) || productOptions.find((item) => item.name.trim().toLowerCase() === normalizedName);
  const filteredProductOptions = productOptions.filter((item) => !form.marketplace || (item.marketplace || "Manual") === form.marketplace || !form.productName.trim()).filter((item) => !normalizedName || item.name.toLowerCase().includes(normalizedName) || (item.marketplace || "Manual").toLowerCase().includes(normalizedName)).slice(0, 6);

  function applySelectedProduct(selected: Product) { onChange({ ...form, productName: selected.name, marketplace: selected.marketplace || form.marketplace || "Manual", costPrice: String(selected.costPrice || ""), sellingPrice: String(selected.sellingPrice || ""), stockInitial: String(selected.stockRemaining || 0), quantitySold: "", otherCost: "" }); setProductPickerOpen(false); }
  function selectExistingProduct(name: string) { const selected = productOptions.find((item) => item.name.trim().toLowerCase() === name.trim().toLowerCase() && (item.marketplace || "Manual") === form.marketplace) || productOptions.find((item) => item.name.trim().toLowerCase() === name.trim().toLowerCase()); if (!selected) { onChange({ ...form, productName: name }); setProductPickerOpen(true); return; } applySelectedProduct(selected); }

  return <section style={cardStyle}>
    <Badge label={c.inputProduct} tone="success" />
    <h2 style={{ marginBottom: 6 }}>{c.addProductTitle}</h2>
    <p style={{ margin: "0 0 14px", color: "#64748b", lineHeight: 1.6, fontSize: 13 }}>{c.productHint}</p>
    <form onSubmit={onSubmit} style={{ display: "grid", gap: 12 }}>
      <select value={form.marketplace} onChange={(e) => onChange({ ...form, marketplace: e.target.value })} style={inputStyle}><option>Shopee</option><option>Tokopedia</option><option>TikTok Shop</option><option>Lazada</option><option>Manual</option></select>
      <div style={{ position: "relative", display: "grid", gap: 8 }}>
        <input value={form.productName} onFocus={() => setProductPickerOpen(true)} onChange={(e) => selectExistingProduct(e.target.value)} placeholder={c.productName} style={inputStyle} autoComplete="off" />
        {productOptions.length ? <div style={{ display: "grid", gap: 8, padding: 10, borderRadius: 16, background: "#f8fafc", border: "1px solid #e2e8f0" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8 }}><small style={{ color: "#64748b", fontWeight: 850 }}>{c.savedProducts}</small><small style={{ color: "#94a3b8" }}>{filteredProductOptions.length ? c.clickToPick : c.noMatch}</small></div>
          {filteredProductOptions.length ? <div style={{ display: "grid", gap: 6, maxHeight: productPickerOpen ? 230 : 112, overflowY: "auto" }}>{filteredProductOptions.map((item) => <button key={`${item.id}-${item.marketplace}`} type="button" onMouseDown={(event) => event.preventDefault()} onClick={() => applySelectedProduct(item)} style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) auto", gap: 8, alignItems: "center", width: "100%", textAlign: "left", border: "1px solid #e2e8f0", background: matchedProduct?.id === item.id ? "#ecfdf5" : "#ffffff", color: "#0f172a", borderRadius: 13, padding: "9px 10px", cursor: "pointer", boxShadow: "0 8px 18px rgba(15,23,42,0.04)" }}><span style={{ minWidth: 0 }}><strong style={{ display: "block", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", fontSize: 13 }}>{item.name}</strong><small style={{ color: "#64748b" }}>{item.marketplace || "Manual"} · {c.stock} {item.stockRemaining} · {c.sold} {item.quantitySold}</small></span><span style={{ color: "#0f766e", fontWeight: 900, fontSize: 12 }}>{c.pick}</span></button>)}</div> : <small style={{ color: "#94a3b8", lineHeight: 1.5 }}>{c.typeOther}</small>}
        </div> : <div style={{ padding: 10, borderRadius: 14, background: "#f8fafc", border: "1px dashed #cbd5e1", color: "#64748b", fontSize: 12, lineHeight: 1.5 }}>{c.noSaved}</div>}
      </div>
      {matchedProduct ? <div style={{ padding: 12, borderRadius: 14, background: "#ecfdf5", border: "1px solid #a7f3d0", color: "#047857", fontSize: 13, lineHeight: 1.55 }}><strong>{c.selected}</strong> {matchedProduct.name} · {c.stockAvailable} {matchedProduct.stockRemaining}. {c.selectedHint} <b>{c.soldField}</b>, {c.selectedHint2}</div> : null}
      <input value={form.costPrice} onChange={(e) => onChange({ ...form, costPrice: e.target.value })} type="number" min="0" placeholder={c.cost} style={inputStyle} />
      <input value={form.sellingPrice} onChange={(e) => onChange({ ...form, sellingPrice: e.target.value })} type="number" min="0" placeholder={c.price} style={inputStyle} />
      <div className="two-grid" style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><input value={form.stockInitial} onChange={(e) => onChange({ ...form, stockInitial: e.target.value })} type="number" min="0" placeholder={matchedProduct ? c.stockAvailableField : c.initialStock} style={inputStyle} /><input value={form.quantitySold} onChange={(e) => onChange({ ...form, quantitySold: e.target.value })} type="number" min="0" placeholder={c.soldField} style={inputStyle} /></div>
      <input value={form.otherCost} onChange={(e) => onChange({ ...form, otherCost: e.target.value })} type="number" min="0" placeholder={c.otherCost} style={inputStyle} />
      <div style={{ display: "grid", gap: 10 }}><button type="submit" disabled={loading} style={{ ...ctaButtonStyle, opacity: loading ? 0.7 : 1 }}>{loading ? c.saving : matchedProduct ? c.saveSaleAdd : c.saveAdd}</button><button type="button" disabled={loading} onClick={onFinish} style={{ ...ghostButtonStyle, opacity: loading ? 0.7 : 1 }}>{matchedProduct ? c.saveSaleFinish : c.saveFinish}</button></div>
    </form>
  </section>;
}

export function ExpensePanel({ expenses, form, metrics, onChange, onSubmit }: { expenses: Expense[]; form: ExpenseFormState; metrics: { totalRevenue: number; totalProfit: number; totalExpenses: number; netCash: number }; onChange: (form: ExpenseFormState) => void; onSubmit: (event: React.FormEvent) => void }) {
  const locale = useDashboardLocale(); const c = COPY[locale];
  return <><section style={cardStyle}><Badge label={c.expenseEngine} tone="warning" /><h2>{c.recordExpense}</h2><p style={{ color: "#64748b", lineHeight: 1.7 }}>{c.expenseDesc}</p><form onSubmit={onSubmit} style={{ display: "grid", gap: 12 }}><input value={form.label} onChange={(e) => onChange({ ...form, label: e.target.value })} placeholder={c.expenseName} style={inputStyle} /><select value={form.category} onChange={(e) => onChange({ ...form, category: e.target.value })} style={inputStyle}>{EXPENSE_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select><div className="two-grid" style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}><input value={form.amount} onChange={(e) => onChange({ ...form, amount: e.target.value })} type="number" min="0" placeholder={c.amount} style={inputStyle} /><input value={form.date} onChange={(e) => onChange({ ...form, date: e.target.value })} type="date" style={inputStyle} /></div><input value={form.notes} onChange={(e) => onChange({ ...form, notes: e.target.value })} placeholder={c.optionalNotes} style={inputStyle} /><button style={ctaButtonStyle}>{c.addExpense}</button></form></section><section style={cardStyle}><Badge label={c.cashflowReal} tone={metrics.netCash >= 0 ? "success" : "danger"} /><h2 style={{ margin: "10px 0" }}>{money(metrics.netCash)} {c.netCashflow}</h2><div className="metrics-grid" style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 12, margin: "16px 0" }}><StatCard label={c.moneyIn} value={money(metrics.totalRevenue)} helper={c.fromSales} tone="blue" /><StatCard label={c.productProfit} value={money(metrics.totalProfit)} helper={c.beforeExpense} tone="success" /><StatCard label={c.moneyOut} value={money(metrics.totalExpenses)} helper={c.expenseHelper} tone="warning" /></div><div style={{ display: "grid", gap: 10 }}>{expenses.map((item) => <div key={item.id} style={{ display: "flex", justifyContent: "space-between", gap: 14, padding: 14, borderRadius: 14, background: "#f8fafc", border: "1px solid #e2e8f0" }}><div><strong>{item.label}</strong><div style={{ color: "#64748b", fontSize: 12 }}>{item.category} · {item.date}</div>{item.notes && <small style={{ color: "#64748b" }}>{item.notes}</small>}</div><strong>{money(item.amount)}</strong></div>)}</div></section></>;
}

export function StockForm({ products, stockMove, onChange, onSubmit }: { products: Product[]; stockMove: { productId: string; type: StockMoveType; qty: string; note: string }; onChange: (stockMove: { productId: string; type: StockMoveType; qty: string; note: string }) => void; onSubmit: (event: React.FormEvent) => void }) {
  const locale = useDashboardLocale(); const c = COPY[locale];
  return <div style={cardStyle}><Badge label={c.stockMove} tone="success" /><h2>{c.updateStock}</h2><p style={{ color: "#64748b", lineHeight: 1.7 }}>{c.stockDesc}</p><form onSubmit={onSubmit} style={{ display: "grid", gap: 12 }}><select value={stockMove.productId} onChange={(e) => onChange({ ...stockMove, productId: e.target.value })} style={inputStyle}><option value="">{c.chooseProduct}</option>{products.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={stockMove.type} onChange={(e) => onChange({ ...stockMove, type: e.target.value as StockMoveType })} style={inputStyle}><option value="in">{c.stockIn}</option><option value="out">{c.stockOut}</option><option value="adjust">{c.stockAdjust}</option></select><input value={stockMove.qty} onChange={(e) => onChange({ ...stockMove, qty: e.target.value })} type="number" min="0" placeholder={c.qty} style={inputStyle} /><input value={stockMove.note} onChange={(e) => onChange({ ...stockMove, note: e.target.value })} placeholder={c.optionalNotes} style={inputStyle} /><button style={ctaButtonStyle}>{c.updateStock}</button></form></div>;
}

export function SaleForm({ products, saleForm, onChange, onSubmit }: { products: Product[]; saleForm: { productId: string; qty: string; otherCost: string }; onChange: (saleForm: { productId: string; qty: string; otherCost: string }) => void; onSubmit: (event: React.FormEvent) => void }) {
  const locale = useDashboardLocale(); const c = COPY[locale];
  return <section style={cardStyle}><Badge label={c.sales} tone="success" /><h2>{c.recordSale}</h2><p style={{ color: "#64748b", lineHeight: 1.7 }}>{c.saleDesc}</p><form onSubmit={onSubmit} style={{ display: "grid", gap: 12 }}><select value={saleForm.productId} onChange={(e) => onChange({ ...saleForm, productId: e.target.value })} style={inputStyle}><option value="">{c.chooseProduct}</option>{products.map((item) => <option key={item.id} value={item.id}>{item.name} - {c.stock} {item.stockRemaining}</option>)}</select><input value={saleForm.qty} onChange={(e) => onChange({ ...saleForm, qty: e.target.value })} type="number" min="1" placeholder={c.qtySold} style={inputStyle} /><input value={saleForm.otherCost} onChange={(e) => onChange({ ...saleForm, otherCost: e.target.value })} type="number" min="0" placeholder={c.extraCost} style={inputStyle} /><button style={ctaButtonStyle}>{c.saveSale}</button></form></section>;
}
