import type { MarketTrend, TrendPeriod } from "./types";

const updated = new Date().toISOString();

function withPeriod(item: Omit<MarketTrend, "lastUpdated">): MarketTrend {
  return { ...item, lastUpdated: updated };
}

export const FALLBACK_MARKET_TRENDS: MarketTrend[] = [
  withPeriod({ id: "seed-d-1", productName: "Serum brightening niacinamide", category: "Beauty", keyword: "serum brightening", marketplace: "Shopee", country: "ID", period: "today", demandScore: 92, growthScore: 88, competitionScore: 74, priceMin: 28000, priceMax: 79000, monthlyUnits: 18400, monthlyRevenue: 912000000, signal: "viral", source: "Fallback market-intelligence seed", sourceKind: "fallback_seed", confidence: 62 }),
  withPeriod({ id: "seed-d-2", productName: "Sunscreen SPF ringan", category: "Beauty", keyword: "sunscreen spf", marketplace: "TikTok Shop", country: "ID", period: "today", demandScore: 90, growthScore: 86, competitionScore: 69, priceMin: 35000, priceMax: 99000, monthlyUnits: 15100, monthlyRevenue: 1087000000, signal: "rising", source: "Fallback live-commerce signal", sourceKind: "fallback_seed", confidence: 61 }),
  withPeriod({ id: "seed-d-3", productName: "Organizer kabel meja kerja", category: "Home Office", keyword: "cable organizer", marketplace: "Shopee", country: "ID", period: "today", demandScore: 76, growthScore: 72, competitionScore: 38, priceMin: 9000, priceMax: 39000, monthlyUnits: 12300, monthlyRevenue: 221000000, signal: "rising", source: "Fallback low-competition signal", sourceKind: "fallback_seed", confidence: 58 }),
  withPeriod({ id: "seed-w-1", productName: "Lampu tidur LED aesthetic", category: "Home Living", keyword: "lampu tidur aesthetic", marketplace: "TikTok Shop", country: "ID", period: "week", demandScore: 84, growthScore: 91, competitionScore: 58, priceMin: 25000, priceMax: 85000, monthlyUnits: 13700, monthlyRevenue: 615000000, signal: "viral", source: "Fallback short-video trend", sourceKind: "fallback_seed", confidence: 63 }),
  withPeriod({ id: "seed-w-2", productName: "Botol minum anak anti bocor", category: "Mom & Baby", keyword: "botol minum anak", marketplace: "Tokopedia", country: "ID", period: "week", demandScore: 81, growthScore: 65, competitionScore: 44, priceMin: 24000, priceMax: 69000, monthlyUnits: 9600, monthlyRevenue: 392000000, signal: "stable", source: "Fallback search-demand signal", sourceKind: "fallback_seed", confidence: 59 }),
  withPeriod({ id: "seed-w-3", productName: "Hampers kopi lokal", category: "F&B", keyword: "hampers kopi", marketplace: "Tokopedia", country: "ID", period: "week", demandScore: 72, growthScore: 77, competitionScore: 41, priceMin: 65000, priceMax: 189000, monthlyUnits: 4100, monthlyRevenue: 486000000, signal: "seasonal", source: "Fallback seasonal demand", sourceKind: "fallback_seed", confidence: 57 }),
  withPeriod({ id: "seed-m-1", productName: "Tas selempang wanita mini", category: "Fashion", keyword: "tas selempang mini", marketplace: "Shopee", country: "ID", period: "month", demandScore: 79, growthScore: 63, competitionScore: 82, priceMin: 39000, priceMax: 149000, monthlyUnits: 21400, monthlyRevenue: 1819000000, signal: "stable", source: "Fallback category ranking", sourceKind: "fallback_seed", confidence: 60 }),
  withPeriod({ id: "seed-m-2", productName: "Instant shawl ironless", category: "Fashion", keyword: "instant shawl", marketplace: "Shopee", country: "MY", period: "month", demandScore: 88, growthScore: 84, competitionScore: 64, priceMin: 32000, priceMax: 118000, monthlyUnits: 14900, monthlyRevenue: 1220000000, signal: "rising", source: "Fallback regional trend", sourceKind: "fallback_seed", confidence: 60 }),
  withPeriod({ id: "seed-m-3", productName: "Minimalist desk mat", category: "Home Office", keyword: "desk mat", marketplace: "Shopee", country: "SG", period: "month", demandScore: 71, growthScore: 68, competitionScore: 29, priceMin: 45000, priceMax: 159000, monthlyUnits: 3900, monthlyRevenue: 392000000, signal: "rising", source: "Fallback low-saturation signal", sourceKind: "fallback_seed", confidence: 56 }),

  withPeriod({ id: "seed-h-1", productName: "Hampers Lebaran premium", category: "Seasonal Gift", keyword: "hampers lebaran", marketplace: "Tokopedia", country: "ID", period: "special_day", demandScore: 91, growthScore: 89, competitionScore: 52, priceMin: 75000, priceMax: 299000, monthlyUnits: 8800, monthlyRevenue: 1610000000, signal: "seasonal", source: "Fallback hari besar Ramadan/Lebaran", sourceKind: "fallback_seed", confidence: 63 }),
  withPeriod({ id: "seed-h-2", productName: "Parcel Natal snack premium", category: "Seasonal Gift", keyword: "parcel natal", marketplace: "Shopee", country: "ID", period: "special_day", demandScore: 86, growthScore: 82, competitionScore: 47, priceMin: 69000, priceMax: 249000, monthlyUnits: 6200, monthlyRevenue: 986000000, signal: "seasonal", source: "Fallback hari besar Natal/Tahun Baru", sourceKind: "fallback_seed", confidence: 60 }),
  withPeriod({ id: "seed-h-3", productName: "Dekorasi pesta ulang tahun anak", category: "Party Supplies", keyword: "dekorasi ulang tahun anak", marketplace: "TikTok Shop", country: "ID", period: "special_day", demandScore: 78, growthScore: 81, competitionScore: 39, priceMin: 18000, priceMax: 89000, monthlyUnits: 10400, monthlyRevenue: 428000000, signal: "seasonal", source: "Fallback momen ulang tahun/event keluarga", sourceKind: "fallback_seed", confidence: 58 }),
  withPeriod({ id: "seed-h-4", productName: "Bendera merah putih set", category: "Event Nasional", keyword: "bendera merah putih", marketplace: "Shopee", country: "ID", period: "special_day", demandScore: 83, growthScore: 90, competitionScore: 43, priceMin: 7000, priceMax: 35000, monthlyUnits: 19800, monthlyRevenue: 287000000, signal: "seasonal", source: "Fallback Hari Kemerdekaan", sourceKind: "fallback_seed", confidence: 59 }),

  withPeriod({ id: "seed-lz-d-1", productName: "Sandal rumah empuk anti slip", category: "Fashion", keyword: "sandal rumah", marketplace: "Lazada", country: "ID", period: "today", demandScore: 80, growthScore: 74, competitionScore: 42, priceMin: 19000, priceMax: 59000, monthlyUnits: 11800, monthlyRevenue: 336000000, signal: "rising", source: "Fallback Lazada price-demand signal", sourceKind: "fallback_seed", confidence: 58 }),
  withPeriod({ id: "seed-lz-w-1", productName: "Earphone bluetooth low latency", category: "Elektronik", keyword: "earphone bluetooth", marketplace: "Lazada", country: "ID", period: "week", demandScore: 86, growthScore: 79, competitionScore: 61, priceMin: 59000, priceMax: 179000, monthlyUnits: 9200, monthlyRevenue: 892000000, signal: "rising", source: "Fallback Lazada electronics trend", sourceKind: "fallback_seed", confidence: 60 }),
  withPeriod({ id: "seed-lz-m-1", productName: "Blender portable USB", category: "Home Appliance", keyword: "blender portable", marketplace: "Lazada", country: "ID", period: "month", demandScore: 77, growthScore: 73, competitionScore: 46, priceMin: 69000, priceMax: 189000, monthlyUnits: 6300, monthlyRevenue: 716000000, signal: "stable", source: "Fallback Lazada monthly ranking", sourceKind: "fallback_seed", confidence: 57 }),
  withPeriod({ id: "seed-lz-h-1", productName: "Koper kabin travel", category: "Travel", keyword: "koper kabin", marketplace: "Lazada", country: "ID", period: "special_day", demandScore: 82, growthScore: 88, competitionScore: 55, priceMin: 199000, priceMax: 499000, monthlyUnits: 3800, monthlyRevenue: 1310000000, signal: "seasonal", source: "Fallback libur sekolah dan akhir tahun", sourceKind: "fallback_seed", confidence: 59 }),
  withPeriod({ id: "seed-tt-w-4", productName: "Parfum roll on viral", category: "Beauty", keyword: "parfum roll on", marketplace: "TikTok Shop", country: "ID", period: "week", demandScore: 88, growthScore: 93, competitionScore: 57, priceMin: 15000, priceMax: 49000, monthlyUnits: 22600, monthlyRevenue: 628000000, signal: "viral", source: "Fallback short-video viral product", sourceKind: "fallback_seed", confidence: 62 }),
  withPeriod({ id: "seed-sh-w-4", productName: "Rak dapur susun minimalis", category: "Home Living", keyword: "rak dapur susun", marketplace: "Shopee", country: "ID", period: "week", demandScore: 83, growthScore: 70, competitionScore: 49, priceMin: 45000, priceMax: 159000, monthlyUnits: 10400, monthlyRevenue: 721000000, signal: "stable", source: "Fallback Shopee home trend", sourceKind: "fallback_seed", confidence: 61 }),
  withPeriod({ id: "seed-tk-m-4", productName: "Kopi susu literan", category: "F&B", keyword: "kopi susu literan", marketplace: "Tokopedia", country: "ID", period: "month", demandScore: 75, growthScore: 71, competitionScore: 37, priceMin: 35000, priceMax: 89000, monthlyUnits: 5200, monthlyRevenue: 314000000, signal: "rising", source: "Fallback Tokopedia local demand", sourceKind: "fallback_seed", confidence: 58 }),

  // Kalodata-like enriched demo seeds: product + seller + creator + video/live/ad signals.
  withPeriod({ id: "kl-week-001", productName: "Parfum roll on viral 10ml", category: "Beauty", keyword: "parfum roll on viral", marketplace: "TikTok Shop", country: "ID", period: "week", demandScore: 91, growthScore: 94, competitionScore: 55, priceMin: 15000, priceMax: 49000, monthlyUnits: 28600, monthlyRevenue: 743600000, sold7d: 7600, sold30d: 28600, revenue7d: 197600000, revenue30d: 743600000, growth7d: 38, growth30d: 72, sellerCount: 146, creatorCount: 82, videoCount: 394, liveCount: 47, adCount: 21, avgRating: 4.7, reviewCount: 4200, opportunityScore: 86, topCreator: "micro-beauty reviewers", topVideoViews: 1800000, signal: "viral", source: "Kalodata-like demo research seed", sourceKind: "kalodata_like_feed", confidence: 78, notes: "Data contoh/estimasi untuk workflow riset manual." }),
  withPeriod({ id: "kl-week-002", productName: "Sunscreen stick travel size", category: "Beauty", keyword: "sunscreen stick", marketplace: "TikTok Shop", country: "ID", period: "week", demandScore: 89, growthScore: 88, competitionScore: 62, priceMin: 28000, priceMax: 89000, monthlyUnits: 19200, monthlyRevenue: 998400000, sold7d: 5100, sold30d: 19200, revenue7d: 265200000, revenue30d: 998400000, growth7d: 25, growth30d: 54, sellerCount: 118, creatorCount: 66, videoCount: 276, liveCount: 31, adCount: 16, avgRating: 4.6, reviewCount: 3600, opportunityScore: 80, topCreator: "skincare daily creators", topVideoViews: 1200000, signal: "rising", source: "Kalodata-like demo research seed", sourceKind: "kalodata_like_feed", confidence: 76, notes: "Cek klaim BPOM/safety sebelum dijual." }),
  withPeriod({ id: "kl-week-003", productName: "Alat pel spray microfiber", category: "Home Living", keyword: "pel spray microfiber", marketplace: "Shopee", country: "ID", period: "week", demandScore: 82, growthScore: 79, competitionScore: 47, priceMin: 39000, priceMax: 129000, monthlyUnits: 15400, monthlyRevenue: 1293600000, sold7d: 3800, sold30d: 15400, revenue7d: 319200000, revenue30d: 1293600000, growth7d: 18, growth30d: 36, sellerCount: 74, creatorCount: 39, videoCount: 122, liveCount: 18, adCount: 11, avgRating: 4.5, reviewCount: 2900, opportunityScore: 78, topCreator: "home cleaning demo", topVideoViews: 760000, signal: "rising", source: "Kalodata-like demo research seed", sourceKind: "kalodata_like_feed", confidence: 74, notes: "Produk mudah didemokan, cocok untuk konten before-after." }),
  withPeriod({ id: "kl-week-004", productName: "Tas selempang puffy wanita", category: "Fashion", keyword: "tas puffy wanita", marketplace: "TikTok Shop", country: "ID", period: "week", demandScore: 86, growthScore: 83, competitionScore: 68, priceMin: 45000, priceMax: 159000, monthlyUnits: 22200, monthlyRevenue: 2264400000, sold7d: 5600, sold30d: 22200, revenue7d: 571200000, revenue30d: 2264400000, growth7d: 21, growth30d: 49, sellerCount: 210, creatorCount: 93, videoCount: 335, liveCount: 52, adCount: 30, avgRating: 4.4, reviewCount: 5100, opportunityScore: 74, topCreator: "fashion OOTD creators", topVideoViews: 1500000, signal: "rising", source: "Kalodata-like demo research seed", sourceKind: "kalodata_like_feed", confidence: 75, notes: "Kompetisi tinggi; perlu diferensiasi warna, bonus, dan foto." }),
  withPeriod({ id: "kl-today-001", productName: "Casing HP MagSafe bening", category: "Aksesoris Gadget", keyword: "casing magsafe bening", marketplace: "Shopee", country: "ID", period: "today", demandScore: 81, growthScore: 86, competitionScore: 52, priceMin: 19000, priceMax: 79000, monthlyUnits: 17100, monthlyRevenue: 837900000, sold7d: 4300, sold30d: 17100, revenue7d: 210700000, revenue30d: 837900000, growth7d: 29, growth30d: 44, sellerCount: 132, creatorCount: 45, videoCount: 160, liveCount: 22, adCount: 13, avgRating: 4.6, reviewCount: 3300, opportunityScore: 79, topCreator: "gadget accessory creators", topVideoViews: 640000, signal: "rising", source: "Kalodata-like demo research seed", sourceKind: "kalodata_like_feed", confidence: 73, notes: "Validasi kompatibilitas model HP sebelum import stok." }),
  withPeriod({ id: "kl-today-002", productName: "Mini chopper USB dapur", category: "Home Appliance", keyword: "mini chopper usb", marketplace: "TikTok Shop", country: "ID", period: "today", demandScore: 84, growthScore: 89, competitionScore: 50, priceMin: 59000, priceMax: 159000, monthlyUnits: 11800, monthlyRevenue: 1286200000, sold7d: 3300, sold30d: 11800, revenue7d: 359700000, revenue30d: 1286200000, growth7d: 32, growth30d: 58, sellerCount: 89, creatorCount: 51, videoCount: 181, liveCount: 26, adCount: 14, avgRating: 4.5, reviewCount: 2400, opportunityScore: 82, topCreator: "alat dapur demo", topVideoViews: 980000, signal: "rising", source: "Kalodata-like demo research seed", sourceKind: "kalodata_like_feed", confidence: 75, notes: "Cek kualitas baterai dan garansi karena rawan retur." }),
  withPeriod({ id: "kl-today-003", productName: "Hair claw clip premium", category: "Fashion", keyword: "hair claw clip", marketplace: "Lazada", country: "ID", period: "today", demandScore: 73, growthScore: 76, competitionScore: 39, priceMin: 7000, priceMax: 39000, monthlyUnits: 18400, monthlyRevenue: 423200000, sold7d: 4500, sold30d: 18400, revenue7d: 103500000, revenue30d: 423200000, growth7d: 17, growth30d: 31, sellerCount: 58, creatorCount: 34, videoCount: 92, liveCount: 11, adCount: 7, avgRating: 4.6, reviewCount: 2100, opportunityScore: 77, topCreator: "daily outfit creators", topVideoViews: 420000, signal: "rising", source: "Kalodata-like demo research seed", sourceKind: "kalodata_like_feed", confidence: 70, notes: "Margin bisa naik dengan bundling isi 3/5." }),
  withPeriod({ id: "kl-month-001", productName: "Botol minum anak karakter", category: "Mom & Baby", keyword: "botol minum anak karakter", marketplace: "Tokopedia", country: "ID", period: "month", demandScore: 80, growthScore: 67, competitionScore: 43, priceMin: 24000, priceMax: 99000, monthlyUnits: 12600, monthlyRevenue: 774900000, sold7d: 2600, sold30d: 12600, revenue7d: 159900000, revenue30d: 774900000, growth7d: 9, growth30d: 22, sellerCount: 64, creatorCount: 28, videoCount: 71, liveCount: 9, adCount: 5, avgRating: 4.7, reviewCount: 3100, opportunityScore: 73, topCreator: "mom review creators", topVideoViews: 360000, signal: "rising", source: "Kalodata-like demo research seed", sourceKind: "kalodata_like_feed", confidence: 72, notes: "Demand stabil, cocok untuk katalog evergreen." }),
  withPeriod({ id: "kl-month-002", productName: "Rak kosmetik acrylic", category: "Beauty Storage", keyword: "rak kosmetik acrylic", marketplace: "Shopee", country: "ID", period: "month", demandScore: 78, growthScore: 74, competitionScore: 41, priceMin: 29000, priceMax: 139000, monthlyUnits: 9800, monthlyRevenue: 823200000, sold7d: 2100, sold30d: 9800, revenue7d: 176400000, revenue30d: 823200000, growth7d: 12, growth30d: 28, sellerCount: 51, creatorCount: 30, videoCount: 84, liveCount: 8, adCount: 6, avgRating: 4.6, reviewCount: 1800, opportunityScore: 76, topCreator: "room makeover creators", topVideoViews: 520000, signal: "rising", source: "Kalodata-like demo research seed", sourceKind: "kalodata_like_feed", confidence: 71, notes: "Visual rapi untuk konten meja rias dan before-after." }),
  withPeriod({ id: "kl-special-001", productName: "Hampers snack premium custom", category: "Seasonal Gift", keyword: "hampers snack premium", marketplace: "Tokopedia", country: "ID", period: "special_day", demandScore: 92, growthScore: 90, competitionScore: 54, priceMin: 79000, priceMax: 299000, monthlyUnits: 8200, monthlyRevenue: 1549800000, sold7d: 1400, sold30d: 8200, revenue7d: 264600000, revenue30d: 1549800000, growth7d: 41, growth30d: 77, sellerCount: 96, creatorCount: 24, videoCount: 65, liveCount: 6, adCount: 18, avgRating: 4.8, reviewCount: 1700, opportunityScore: 85, topCreator: "gift wrapping creators", topVideoViews: 330000, signal: "seasonal", source: "Kalodata-like demo research seed", sourceKind: "kalodata_like_feed", confidence: 77, notes: "Naik saat Lebaran, Natal, wisuda, dan momen kantor." }),
  withPeriod({ id: "kl-special-002", productName: "Dekorasi ulang tahun anak paket lengkap", category: "Party Supplies", keyword: "dekorasi ulang tahun anak", marketplace: "TikTok Shop", country: "ID", period: "special_day", demandScore: 79, growthScore: 84, competitionScore: 42, priceMin: 18000, priceMax: 99000, monthlyUnits: 13300, monthlyRevenue: 778050000, sold7d: 2900, sold30d: 13300, revenue7d: 169650000, revenue30d: 778050000, growth7d: 24, growth30d: 46, sellerCount: 69, creatorCount: 37, videoCount: 116, liveCount: 12, adCount: 8, avgRating: 4.5, reviewCount: 2200, opportunityScore: 81, topCreator: "party decor creators", topVideoViews: 690000, signal: "seasonal", source: "Kalodata-like demo research seed", sourceKind: "kalodata_like_feed", confidence: 73, notes: "Cocok untuk variasi tema dan paket bundling." }),

];

export function fallbackForPeriod(period: TrendPeriod) {
  return FALLBACK_MARKET_TRENDS.filter((item) => item.period === period);
}
