import type { MarketTrend, TrendPeriod } from "./types";

const updated = new Date().toISOString();

function withPeriod(item: Omit<MarketTrend, "lastUpdated">): MarketTrend {
  return { ...item, lastUpdated: updated };
}

export const FALLBACK_MARKET_TRENDS: MarketTrend[] = [
  withPeriod({ id: "seed-d-1", productName: "Serum brightening niacinamide", category: "Beauty", keyword: "serum brightening", marketplace: "Shopee", country: "ID", period: "today", demandScore: 92, growthScore: 88, competitionScore: 74, priceMin: 28000, priceMax: 79000, monthlyUnits: 18400, monthlyRevenue: 912000000, signal: "viral", source: "Fallback market-intelligence seed", sourceKind: "fallback_seed", confidence: 62 }),
  withPeriod({ id: "seed-d-2", productName: "Sunscreen SPF ringan", category: "Beauty", keyword: "sunscreen spf", marketplace: "TikTok Shop", country: "ID", period: "today", demandScore: 90, growthScore: 86, competitionScore: 69, priceMin: 35000, priceMax: 99000, monthlyUnits: 15100, monthlyRevenue: 1087000000, signal: "rising", source: "Fallback live-commerce signal", sourceKind: "fallback_seed", confidence: 61 }),
  withPeriod({ id: "seed-d-3", productName: "Organizer kabel meja kerja", category: "Home Office", keyword: "cable organizer", marketplace: "Shopee", country: "ID", period: "today", demandScore: 76, growthScore: 72, competitionScore: 38, priceMin: 9000, priceMax: 39000, monthlyUnits: 12300, monthlyRevenue: 221000000, signal: "rising", source: "Fallback low-competition signal", sourceKind: "fallback_seed", confidence: 58 }),
  withPeriod({ id: "seed-w-1", productName: "Lampu tidur LED aesthetic", category: "Home Living", keyword: "lampu tidur aesthetic", marketplace: "TikTok Shop", country: "ID", period: "week", demandScore: 84, growthScore: 91, competitionScore: 58, priceMin: 25000, priceMax: 85000, monthlyUnits: 13700, monthlyRevenue: 615000000, signal: "viral", source: "Fallback short-video trend", sourceKind: "fallback_seed", confidence: 63 }),
  withPeriod({ id: "seed-w-2", productName: "Botol minum anak anti bocor", category: "Mom & Baby", keyword: "botol minum anak", marketplace: "Tokopedia", country: "ID", period: "week", demandScore: 81, growthScore: 65, competitionScore: 44, priceMin: 24000, priceMax: 69000, monthlyUnits: 9600, monthlyRevenue: 392000000, signal: "stable", source: "Fallback search-demand signal", sourceKind: "fallback_seed", confidence: 59 }),
  withPeriod({ id: "seed-w-3", productName: "Hampers kopi lokal", category: "F&B", keyword: "hampers kopi", marketplace: "Tokopedia", country: "ID", period: "week", demandScore: 72, growthScore: 77, competitionScore: 41, priceMin: 65000, priceMax: 189000, monthlyUnits: 4100, monthlyRevenue: 486000000, signal: "seasonal", source: "Fallback seasonal demand", sourceKind: "fallback_seed", confidence: 57 }),
  withPeriod({ id: "seed-m-1", productName: "Tas selempang wanita mini", category: "Fashion", keyword: "tas selempang mini", marketplace: "Shopee", country: "ID", period: "month", demandScore: 79, growthScore: 63, competitionScore: 82, priceMin: 39000, priceMax: 149000, monthlyUnits: 21400, monthlyRevenue: 1819000000, signal: "stable", source: "Fallback category ranking", sourceKind: "fallback_seed", confidence: 60 }),
  withPeriod({ id: "seed-m-2", productName: "Instant shawl ironless", category: "Fashion", keyword: "instant shawl", marketplace: "Shopee", country: "MY", period: "month", demandScore: 88, growthScore: 84, competitionScore: 64, priceMin: 32000, priceMax: 118000, monthlyUnits: 14900, monthlyRevenue: 1220000000, signal: "rising", source: "Fallback regional trend", sourceKind: "fallback_seed", confidence: 60 }),
  withPeriod({ id: "seed-m-3", productName: "Minimalist desk mat", category: "Home Office", keyword: "desk mat", marketplace: "Shopee", country: "SG", period: "month", demandScore: 71, growthScore: 68, competitionScore: 29, priceMin: 45000, priceMax: 159000, monthlyUnits: 3900, monthlyRevenue: 392000000, signal: "rising", source: "Fallback low-saturation signal", sourceKind: "fallback_seed", confidence: 56 }),

  withPeriod({ id: "seed-h-1", productName: "Hampers Lebaran premium", category: "Seasonal Gift", keyword: "hampers lebaran", marketplace: "Tokopedia", country: "ID", period: "special_day", demandScore: 91, growthScore: 89, competitionScore: 52, priceMin: 75000, priceMax: 299000, monthlyUnits: 8800, monthlyRevenue: 1610000000, signal: "seasonal", source: "Fallback hari besar Ramadan/Lebaran", sourceKind: "fallback_seed", confidence: 63 }),
  withPeriod({ id: "seed-h-2", productName: "Parcel Natal snack premium", category: "Seasonal Gift", keyword: "parcel natal", marketplace: "Shopee", country: "ID", period: "special_day", demandScore: 86, growthScore: 82, competitionScore: 47, priceMin: 69000, priceMax: 249000, monthlyUnits: 6200, monthlyRevenue: 986000000, signal: "seasonal", source: "Fallback hari besar Natal/Tahun Baru", sourceKind: "fallback_seed", confidence: 60 }),
  withPeriod({ id: "seed-h-3", productName: "Dekorasi pesta ulang tahun anak", category: "Party Supplies", keyword: "dekorasi ulang tahun anak", marketplace: "TikTok Shop", country: "ID", period: "special_day", demandScore: 78, growthScore: 81, competitionScore: 39, priceMin: 18000, priceMax: 89000, monthlyUnits: 10400, monthlyRevenue: 428000000, signal: "seasonal", source: "Fallback momen ulang tahun/event keluarga", sourceKind: "fallback_seed", confidence: 58 }),
  withPeriod({ id: "seed-h-4", productName: "Bendera merah putih set", category: "Event Nasional", keyword: "bendera merah putih", marketplace: "Shopee", country: "ID", period: "special_day", demandScore: 83, growthScore: 90, competitionScore: 43, priceMin: 7000, priceMax: 35000, monthlyUnits: 19800, monthlyRevenue: 287000000, signal: "seasonal", source: "Fallback Hari Kemerdekaan", sourceKind: "fallback_seed", confidence: 59 }),

  withPeriod({ id: "seed-lz-d-1", productName: "Sandal rumah empuk anti slip", category: "Fashion", keyword: "sandal rumah", marketplace: "Lazada", country: "ID", period: "today", demandScore: 80, growthScore: 74, competitionScore: 42, priceMin: 19000, priceMax: 59000, monthlyUnits: 11800, monthlyRevenue: 336000000, signal: "rising", source: "Fallback Lazada price-demand signal", sourceKind: "fallback_seed", confidence: 58 }),
  withPeriod({ id: "seed-lz-w-1", productName: "Earphone bluetooth low latency", category: "Elektronik", keyword: "earphone bluetooth", marketplace: "Lazada", country: "ID", period: "week", demandScore: 86, growthScore: 79, competitionScore: 61, priceMin: 59000, priceMax: 179000, monthlyUnits: 9200, monthlyRevenue: 892000000, signal: "rising", source: "Fallback Lazada electronics trend", sourceKind: "fallback_seed", confidence: 60 }),
  withPeriod({ id: "seed-lz-m-1", productName: "Blender portable USB", category: "Home Appliance", keyword: "blender portable", marketplace: "Lazada", country: "ID", period: "month", demandScore: 77, growthScore: 73, competitionScore: 46, priceMin: 69000, priceMax: 189000, monthlyUnits: 6300, monthlyRevenue: 716000000, signal: "stable", source: "Fallback Lazada monthly ranking", sourceKind: "fallback_seed", confidence: 57 }),
  withPeriod({ id: "seed-lz-h-1", productName: "Koper kabin travel", category: "Travel", keyword: "koper kabin", marketplace: "Lazada", country: "ID", period: "special_day", demandScore: 82, growthScore: 88, competitionScore: 55, priceMin: 199000, priceMax: 499000, monthlyUnits: 3800, monthlyRevenue: 1310000000, signal: "seasonal", source: "Fallback libur sekolah dan akhir tahun", sourceKind: "fallback_seed", confidence: 59 }),
  withPeriod({ id: "seed-tt-w-4", productName: "Parfum roll on viral", category: "Beauty", keyword: "parfum roll on", marketplace: "TikTok Shop", country: "ID", period: "week", demandScore: 88, growthScore: 93, competitionScore: 57, priceMin: 15000, priceMax: 49000, monthlyUnits: 22600, monthlyRevenue: 628000000, signal: "viral", source: "Fallback short-video viral product", sourceKind: "fallback_seed", confidence: 62 }),
  withPeriod({ id: "seed-sh-w-4", productName: "Rak dapur susun minimalis", category: "Home Living", keyword: "rak dapur susun", marketplace: "Shopee", country: "ID", period: "week", demandScore: 83, growthScore: 70, competitionScore: 49, priceMin: 45000, priceMax: 159000, monthlyUnits: 10400, monthlyRevenue: 721000000, signal: "stable", source: "Fallback Shopee home trend", sourceKind: "fallback_seed", confidence: 61 }),
  withPeriod({ id: "seed-tk-m-4", productName: "Kopi susu literan", category: "F&B", keyword: "kopi susu literan", marketplace: "Tokopedia", country: "ID", period: "month", demandScore: 75, growthScore: 71, competitionScore: 37, priceMin: 35000, priceMax: 89000, monthlyUnits: 5200, monthlyRevenue: 314000000, signal: "rising", source: "Fallback Tokopedia local demand", sourceKind: "fallback_seed", confidence: 58 }),
];

export function fallbackForPeriod(period: TrendPeriod) {
  return FALLBACK_MARKET_TRENDS.filter((item) => item.period === period);
}
